-- 코드를 작성해주세요
SELECT F1.ID, FN.FISH_NAME, F1.LENGTH LENGTH
FROM FISH_INFO F1
JOIN FISH_NAME_INFO FN 
ON F1.FISH_TYPE = FN.FISH_TYPE
WHERE F1.LENGTH = (SELECT MAX(F2.LENGTH)
                  FROM FISH_INFO F2
                  WHERE F1.FISH_TYPE = F2.FISH_TYPE)
ORDER BY F1.ID