-- 코드를 작성해주세요
SELECT F.ID, FN.FISH_NAME, F.LENGTH LENGTH
FROM FISH_INFO F
JOIN FISH_NAME_INFO FN 
ON F.FISH_TYPE = FN.FISH_TYPE
WHERE F.LENGTH = (SELECT MAX(G.LENGTH)
                  FROM FISH_INFO G
                  WHERE F.FISH_TYPE = G.FISH_TYPE)
ORDER BY F.ID
